# Generated by Django 5.1.4 on 2024-12-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CREDapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='sprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='sname',
            new_name='sName',
        ),
        migrations.RenameField(
            model_name='shoes',
            old_name='stype',
            new_name='sType',
        ),
    ]
